### ISSUE TITLE
Flag for debug output

### ISSUE THREAD

**Issue by moritonal** [LostInBrittany/ace-widget#14]
Hi Horacio

Hope all's been well since the conference.

The element currently outputs a lot of debug info. It'd be nice to have a flag to control this behaviour.

**Comment by moritonal** [comment]
I am working on a pull-request now.

**Comment by LostInBrittany** [comment]
That's great! Thanks for the issue and the PR!

Yesterday I had just the same comment for another of my elements, [LostInBrittany/granite-clipboard](https://github.com/LostInBrittany/granite-clipboard/) and I [added a verbose attribute](https://github.com/LostInBrittany/granite-clipboard/issues/3) to keep noise low. 

Would it be possible to rename your `debug` attribute to `verbose` in order to keep coherence in the element collection?

**Comment by moritonal** [comment]
Good idea with the verbose flag, changed now.

**Comment by LostInBrittany** [comment]
Thanks a lot! I merged your PR
